flask-example/app/models.py
from app import db, bcrypt


class User(db.Model):
    __tablename__ = 'users'

    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(64), index=True, unique=True)
    password_hash = db.Column(db.String(128))
    email = db.Column(db.String(120), index=True, unique=True)

    def __init__(self, username, password, email):
        self.username = username
        self.password_hash = self.hash_password(password)
        self.email = email

    def __repr__(self):
        return f'<User {self.username}>'

    def hash_password(self, password):
        return bcrypt.generate_password_hash(password).decode('utf-8')

    def check_password(self, password):
        return bcrypt.check_password_hash(self.password_hash, password)

flask-example/app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import (
    StringField, PasswordField, SubmitField, BooleanField)
from wtforms.validators import (
    InputRequired, Length, Email, EqualTo
)

class RegistrationForm(FlaskForm):

    email = StringField(
        'Email',
        validators=[InputRequired(),
                    Email()])

    username = StringField(
        'Username',
        validators=[InputRequired(),
                    Length(min=2, max=20)])

    password = PasswordField(
        'Password',
        validators=[InputRequired()])

    confirm_password = PasswordField(
        'Confirm Password',
        validators=[InputRequired(),
                    EqualTo('password')])

    submit = SubmitField('Register')

class LoginForm(FlaskForm):

    username = StringField(
        'Username',
        validators=[InputRequired(),
                    Length(min=2, max=20)])

    password = PasswordField(
        'Password',
        validators=[InputRequired()])

    remember_me = BooleanField('Remember Me')
    submit = SubmitField('Login')

flask-example/app.py
from app import app

if __name__ == '__main__':
    print(app.config)
    app.run()

flask-example/app/__init__.py
from flask import Flask
from config import BaseConfig
from flask_sqlalchemy import SQLAlchemy

app = Flask(__name__)
app.config.from_object(BaseConfig)
db = SQLAlchemy(app)

from .main.routes import main_bp
from .admin_api.endpoints import api_bp

app.register_blueprint(main_bp)
app.register_blueprint(api_bp, url_prefix='/api')

flask-example/app/admin_api/__init__.py
from flask import Blueprint

# Blueprint Configuration
api_bp = Blueprint(
    'api', __name__,
    template_folder='templates',
    static_folder='static'
)

flask-example/app/main/__init__.py
from flask import Blueprint

# Blueprint Configuration
main_bp = Blueprint(
    'main', __name__,
    template_folder='templates',
    static_folder='static'
)

from . import routes

flask-example/app/main/routes.py
from flask import (
    render_template,
    redirect, url_for, flash)
from werkzeug.security import (
    generate_password_hash,
    check_password_hash)
from app import db
from . import main_bp
from app.models import User
from .forms import RegistrationForm, LoginForm


@main_bp.route('/')
def index():
    return render_template('index.html')


@main_bp.route('/registration', methods=['GET', 'POST'])
def register():
    form = RegistrationForm()

    if form.validate_on_submit():
        # Check if the user already exists
        email = form.email.data

        user = User.query.filter_by(email=email).first()

        if user is None:
            user = User(
                username=form.username.data,
                password_hash=generate_password_hash(form.password.data),
                email=form.email.data)
            db.session.add(user)
            db.session.commit()

        else:
            flash("Already exists. Log in instead.")

        return redirect(url_for('main.login'))
    return render_template('registration.html', title='Register', form=form)


@main_bp.route('/login', methods=['GET', 'POST'])
def login():
    form = LoginForm()
    n_attempts = 3

    if form.validate_on_submit():
        user = User.query.filter_by(username=form.username.data).first()
        if user is not None:
            to_check = user.password_hash
            if check_password_hash(to_check, form.password.data):
                n_attempts = 3
                return redirect(url_for('main.home'))
            else:
                n_attempts -= 1
                flash(f'Invalid credentials - {n_attempts} attempts left.')
                return redirect(url_for('main.login'))
    return render_template('login.html', title='Log In', form=form)


@main_bp.route('/home')
def home():
    return "Logged in"

flask-example/app/routes.py
from flask import render_template, redirect, url_for, flash
from app import app, db
from app.forms import RegistrationForm, LoginForm
from app.models import User


@app.route('/')
def index():
    return render_template('index.html')


@app.route('/registration', methods=['GET', 'POST'])
def register():
    form = RegistrationForm()

    if form.validate_on_submit():
        # Check if the user already exists
        email = form.email.data

        user = User.query.filter_by(email=email).first()

        if user is None:
            user = User(
                username=form.username.data,
                password=form.password.data,
                email=form.email.data)

            db.session.add(user)
            db.session.commit()

        else:
            flash("Already exists. Log in instead.")

        return redirect(url_for('login'))
    return render_template('registration.html', title='Register', form=form)


@app.route('/login', methods=['GET', 'POST'])
def login():
    form = LoginForm()
    n_attempts = 3

    if form.validate_on_submit():
        user = User.query.filter_by(username=form.username.data).first()
        if user is not None:
            # to_check = user.password_hash
            if user.check_password(form.password.data):
                print("Success")
                n_attempts = 3
                return redirect(url_for('home'))
            else:
                print("Failure")
                n_attempts -= 1
                flash(f'Invalid credentials - {n_attempts} attempts left.')
                return redirect(url_for('login'))
    return render_template('login.html', title='Log In', form=form)


@app.route('/home')
def home():
    return "Logged in"

flask-example/app/templates/home.html
<!DOCTYPE html>
<html>
<head>
    <title></title>
</head>
<body>

</body>
</html>

flask-example/app/templates/index.html
{% extends "layout.html" %}

{% block content %}
This is the home page
{% endblock %}

flask-example/app/templates/layout.html
<!DOCTYPE html>
<html>
<head>
    <title>Flask Example - {{ title|default("Home", true) }}</title>
</head>
<body>
    <div>
        <h3>Flask Example:
        <a href="{{ url_for('main.register') }}">Register</a>
        <a href="{{ url_for('main.login') }}">Login</a></h3>
    </div>
    {% with messages = get_flashed_messages() %}
        {% if messages %}
            <ul>
                {% for message in messages %}
                    <ul>{{ message }}</ul>
                {% endfor %}
             </ul>
        {% endif %}
    {% endwith %}

    {% block content %}{% endblock content %}
</body>
</html>

flask-example/app/templates/login.html
{% extends "layout.html" %}
{% block content %}
<div>
    <form method="POST" action="">
        <fieldset>
            <legend>Log In</legend>

            <div>
                {{ form.username.label }}
                {{ form.username }}
                <ul>
                    {% for error in form.username.errors %}
                        <span style="color: red;">[{{ error }}]</span>
                    {% endfor %}
                </ul>
            </div>

            <div>
                {{ form.password.label }}
                {{ form.password }}
                <ul>
                    {% for error in form.password.errors %}
                        <span style="color: red;">[{{ error }}]</span>
                    {% endfor %}
                </ul>
            </div>
        <div>
            <p>{{ form.remember_me() }} {{ form.remember_me.label}}</p>
            <p>{{ form.submit() }}</p>
        </div>

        </fieldset>

        {{ form.csrf_token }}

    </form>

</div>

{% endblock content %}

flask-example/app/templates/registration.html
{% extends "layout.html" %}
{% block content %}
<div>
    <form method="POST" action="">
        {{ form.hidden_tag() }}
        <fieldset>
            <legend>Sign Up</legend>
            <div>
                {{ form.email.label }}
                {{ form.email }}
                <ul>
                    {% for error in form.email.errors %}
                        <span style="color: red;">[{{ error }}]</span>
                    {% endfor %}
                </ul>
            </div>

            <div>
                {{ form.username.label }}
                {{ form.username }}
                <ul>
                    {% for error in form.username.errors %}
                        <span style="color: red;">[{{ error }}]</span>
                    {% endfor %}
                </ul>
            </div>

            <div>
                {{ form.password.label }}
                {{ form.password }}
                <ul>
                    {% for error in form.password.errors %}
                        <span style="color: red;">[{{ error }}]</span>
                    {% endfor %}
                </ul>
            </div>

            <div>
                {{ form.confirm_password.label }}
                {{ form.confirm_password }}
                <ul>
                    {% for error in form.confirm_password.errors %}
                        <span style="color: red;">[{{ error }}]</span>
                    {% endfor %}
                </ul>
            </div>
        </fieldset>
        <div>
            {{ form.submit() }}
        </div>

        {{ form.csrf_token }}

    </form>

</div>

{% endblock content %}